### ISSUE TITLE
is the 4Mbit FRAM supported?

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_FRAM#19]
According the the guide, https://learn.adafruit.com/spi-fram-2mbit-4mbit 
this library should be used with the new 2Mbit and 4Mbit FRAM breakouts, but it is not working.
I have a 4Mbit FRAM breakout connected to a  feather_m4_express and tried as below.

Note that len(fram) only shows 8192  -- should be 512K
Writing to the board does not appear to work.

```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.3-180-g7611e71a1 on 2020-09-12; Adafruit Feather M4 Express with samd51j19
>>> 
>>> import board
>>> import busio
>>> import digitalio
>>> import adafruit_fram
>>> 
>>> ## Create a FRAM object.
>>> spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
>>> cs = digitalio.DigitalInOut(board.D5)
>>> fram = adafruit_fram.FRAM_SPI(spi, cs)
>>> fram[0]
bytearray(b'\xff')
>>> len(fram)
8192
>>> fram[0]=1
>>> fram[0]
bytearray(b'\xff')
>>> 
```

edited to add -- it works fine with an 8Kbyte FRAM

looking at the code -- it does not appear to be able to handle the larger parts
https://github.com/adafruit/Adafruit_CircuitPython_FRAM/blob/master/adafruit_fram.py#L55

**Comment by ladyada** [comment]
hmm you may have to pass in the size (the library doesnt autodetect)
https://github.com/adafruit/Adafruit_CircuitPython_FRAM/blob/master/adafruit_fram.py#L69
does it work then?

**Comment by jerryneedell** [comment]
well, sort of  -- I changed _MAX_SIZE_SPI to const(524288) 
and it works for low addresses but not for the full address range.
looking into it...
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-beta.0 on 2020-09-21; Saola 1 w/Wrover with ESP32S2
>>> import board
>>> import busio
>>> import digitalio
>>> import adafruit_fram
>>> 
>>> spi = busio.SPI(board.IO36, MOSI=board.IO35, MISO=board.IO37)
... 
>>> spi = busio.SPI(board.IO36, MOSI=board.IO35, MISO=board.IO37)
>>> cs = digitalio.DigitalInOut(board.IO3)
>>> fram = adafruit_fram.FRAM_SPI(spi, cs)
>>> fram[0]
bytearray(b'\x01')
>>> fram[0] = 5
>>> fram[0]
bytearray(b'\x05')
>>> fram[0:10]
bytearray(b'\x05\x02\x03\x02\x03\x04\x05\x06\x00\x00\x00')
>>> len(fram)
524288
>>> fram[524287] = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_fram.py", line 192, in __setitem__
  File "adafruit_fram.py", line 366, in _write
  File "adafruit_fram.py", line 362, in _write
OverflowError: value must fit in 1 byte(s)
>>> 
```

**Comment by ladyada** [comment]
do you want to investigate or i can?

**Comment by jerryneedell** [comment]
ok -- this needs to be expanded
https://github.com/adafruit/Adafruit_CircuitPython_FRAM/blob/master/adafruit_fram.py#L363

**Comment by jerryneedell** [comment]
Both the read and write need to be modified to handle the larger range. I'll be happy to give it a shot, but you are welcom to do it if you want it faster.
Also, should the max size kwarg be added to the init section for the FRAM_SPI - it can't be passed in now. Or do you want the size alway to be 512K from now on?

**Comment by jerryneedell** [comment]
@ladyada At first I thought it would be simple changes to expand the "address" but I think I need to look at the data sheets to see how to specify the address for the larger parts. It is not clear to me why it works since the MB85RS4MT expects a 24 bit address....The problem also will be  how to keep it compatible with the smaller parts that expect a 16 bit address field.

**Comment by ladyada** [comment]
yah thats what we do in arduino
https://github.com/adafruit/Adafruit_FRAM_SPI/blob/master/Adafruit_FRAM_SPI.cpp#L81
honestly we could detect it from the JEDEC tho. im in meetings today, if you want to take a stab at it i can review!

**Comment by jerryneedell** [comment]
OK -- I'll give it a shot.

**Comment by jerryneedell** [comment]
Just to clarify -- IT does NOT work on the MB85RS4MT  just wit the larger _MAX_SIZE -- I forgot I had put the a 64K part in to check it :-(  -- At least it makes sense now -- I'll work on a fix...

**Comment by jerryneedell** [comment]
OK -- good progress -- I can now write and read to the whole part -- that part was easy -- now to make it backward compatible,..
```Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-beta.0 on 2020-09-21; Saola 1 w/Wrover with ESP32S2
>>> import board
>>> import busio
>>> import digitalio
>>> import adafruit_fram
>>> spi = busio.SPI(board.IO36, MOSI=board.IO35, MISO=board.IO37)
... 
>>> spi = busio.SPI(board.IO36, MOSI=board.IO35, MISO=board.IO37)
>>> cs = digitalio.DigitalInOut(board.IO3)
>>> fram = adafruit_fram.FRAM_SPI(spi, cs)
>>> fram[0]
bytearray(b'\x00')
>>> fram[0]=1
>>> fram[0]
bytearray(b'\x01')
>>> fram[524287]
bytearray(b'\x00')
>>> fram[524287]=1
>>> fram[524287]
bytearray(b'\x01')
>>> 
```
