### ISSUE TITLE
Update FRAM Learn Guides With CircuitPython

### ISSUE THREAD

**Issue by sommersoft** [adafruit/Adafruit_CircuitPython_FRAM#2]
Update Adafruit Learn Guides for both FRAM chips.

- [x] I2C [here](https://learn.adafruit.com/adafruit-i2c-fram-breakout?view=all)
- [x] SPI [here](https://learn.adafruit.com/adafruit-spi-fram-breakout?view=all)

**Comment by kattni** [comment]
@sommersoft Were you interested in doing these updates? Now we have both features added!

**Comment by sommersoft** [comment]
Yep, I can definitely do them. Just need to be added to them.

**Comment by kattni** [comment]
Added! Thank you!
