### ISSUE TITLE
Remote I/O error

### ISSUE THREAD

**Issue by StevenBruinen** [adafruit/Adafruit_CircuitPython_FRAM#8]
I've connected the FRAM module to my Raspberry Pi via I2C. But when running the example code I get an 'Remote I/O error' 

The device is available when running: 
```
i2cdetect -y 1

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
40: -- -- -- -- 44 -- -- -- 48 -- -- -- -- -- -- --
50: 50 UU -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
It also responds to:
```
i2cget -y 1 0x50
0x00
```

But when running the provided example code:
```
python3 fram.py

Traceback (most recent call last):
  File "fram.py", line 9, in <module>
    fram = adafruit_fram.FRAM_I2C(i2c)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_fram.py", line 211, in __init__
    dev_id.readinto(read_buf)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 97, in readinto
    self.i2c.readfrom_into(self.device_address, buf, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 55, in readfrom_into
    return self._i2c.readfrom_into(address, buffer, stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 44, in readfrom_into
    readin = self._i2c_bus.read_bytes(address, end-start)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 155, in read_bytes
    return self._device.read(number)
OSError: [Errno 121] Remote I/O error
```
Any ideas on how to get this working?

**Comment by ladyada** [comment]
i know what this is 
https://github.com/adafruit/Adafruit_CircuitPython_FRAM/blob/master/adafruit_fram.py#L210
should be converted to a single `write_then_readinto` because linux doesnt support I2C `stop=True` in two calls, must be in one call (yay)

@makermelissa you had this set up recently, is this something you can swap and test - if its the write_then_readinto call and works on an M0 it should fix it in Python by default

**Comment by makermelissa** [comment]
Sure, I can take a look at it.

**Comment by makermelissa** [comment]
I'm so sorry, but I seem to have temporarily misplaced my FRAM during my move. 🙁I just looked in all the places I thought it might be, but was unable to locate it.

**Comment by jerryneedell** [comment]
I have one and I can look into this if yours does not appear soon.

**Comment by makermelissa** [comment]
Thanks. I'm still looking and hoping.

**Comment by jerryneedell** [comment]
I know that problem. Usually I blame the cats ;-)

**Comment by makermelissa** [comment]
That does happen all too often.

**Comment by makermelissa** [comment]
Ok @jerryneedell, I gave up on finding it this week so please give it a try. Thanks.

**Comment by jerryneedell** [comment]
np -- just finished testing - will post a PR in a few minutes.

**Comment by StevenBruinen** [comment]
Just tried the new code and it worked perfectly. 
No more errors when reading and writing to the FRAM in Python3 on a Raspberry Pi. \0/

 Thank you all very much for your support!
